
default_settings:
  trainer_type: ppo
  keep_checkpoints: 5
  max_steps: 50000000
  time_horizon: 1000
  summary_freq: 2000
  threaded: true
  hyperparameters:
    batch_size: 2048
    buffer_size: 20480
    learning_rate: 0.0003
    beta: 0.005
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 3
    learning_rate_schedule: constant
  network_settings:
    normalize: true
    hidden_units: 256
    num_layers: 2
    vis_encode_type: simple
  reward_signals:
    extrinsic:
      gamma: 0.99
      strength: 1.0
    curiosity:
      gamma: 0.99
      strength: 0.02
      encoding_size: 256
      learning_rate: 0.0003
           
environment_parameters:
  level:
    curriculum:
      - name: Level0 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0
          require_reset: false
          behavior: STurret1
        value: 0.0
      - name: Level1 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 30
          require_reset: false
          behavior: STurret1
        value: 1.0
      - name: Level2# The '-' is important as this is a list
        value: 2.0

        completion_criteria:
          measure: reward
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 31
          require_reset: false
          behavior: STurret1

      - name: Level3 # The '-' is important as this is a list
        value: 3.0

#checkpoint_settings:
#    initialize_from: results/se10/YTDriver2
behaviors:
   
    YTDriver2:
       
        network_settings:
            normalize: true
            hidden_units: 64
            num_layers: 2
            vis_encode_type: simple
    
    YTDriver3:
        trainer_type: ppo
        keep_checkpoints: 5
        max_steps: 50000000
        time_horizon: 1000
        summary_freq: 2000
        threaded: true
        hyperparameters:
            batch_size: 2048
            buffer_size: 20480
            learning_rate: 0.0003
            beta: 0.005
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 3
            learning_rate_schedule: constant
        network_settings:
            normalize: true
            hidden_units: 256
            num_layers: 1
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
            curiosity:
                gamma: 0.99
                strength: 0.02
                encoding_size: 256
                learning_rate: 0.0003
    YTDriver4:
        trainer_type: ppo
        keep_checkpoints: 5
        max_steps: 50000000
        time_horizon: 1000
        summary_freq: 2000
        threaded: true
        hyperparameters:
            batch_size: 2048
            buffer_size: 20480
            learning_rate: 0.0003
            beta: 0.005
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 3
            learning_rate_schedule: constant
        network_settings:
            normalize: true
            hidden_units: 128
            num_layers: 2
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
            curiosity:
                gamma: 0.99
                strength: 0.02
                encoding_size: 256
                learning_rate: 0.0003
